# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apigetaway:
    image: apigetaway
    build:
      context: .
      dockerfile: api_getaway/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5200:5200
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
